# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-09 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el objeto fue creado', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha en que el objeto fue modificado', verbose_name='modified at')),
                ('name', models.CharField(max_length=140, verbose_name=b'circle name')),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('about', models.CharField(max_length=255, verbose_name=b'circle description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=b'circles/pictures')),
                ('rides_offered', models.PositiveIntegerField(default=0)),
                ('rides_taken', models.PositiveIntegerField(default=0)),
                ('verfied', models.BooleanField(default=False, verbose_name=b'verified circle')),
                ('is_public', models.BooleanField(default=True)),
                ('is_limited', models.BooleanField(default=False, help_text=b'limited circles', verbose_name=b'limited')),
                ('members_limit', models.PositiveIntegerField(default=0, help_text=b'Si el circulo tiene limite')),
            ],
            options={
                'ordering': ['-rides_taken', '-rides_offered'],
                'abstract': False,
                'get_latest_by': 'created',
            },
        ),
    ]
